import Head from 'next/head'
import styles from '../styles/Home.module.css'

import axios from 'axios'
import { useEffect } from 'react';

const Home = () => {


  useEffect(() => {

    getAxios()

  }, [])

  const getAxios = async () => {
    const response = await axios.get('/api/hello')
    console.log(response)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <h1>Hola Mundo</h1>
    </div>
  )
}

export default Home
